export default [{
  menu: '数据',
  icon: 'icon-wodegongzuo',
  children: [{
    menu: '数据进制转换',
    path: '/data/transfer',
    children: []
  }, {
    menu: '判断数据类型',
    path: '/data/judge-data-type',
    children: []
  }, {
    menu: '判断对象是否为{}',
    path: '/data/judge-obj-empty',
    children: []
  }, {
    menu: '判断数据是否是NaN',
    path: '/data/judge-data-nan',
    children: []
  }, {
    menu: '停止对象数据扩展',
    path: '/data/object-prevent-extension',
    children: []
  }, {
    menu: '判断数据是否是有限的',
    path: '/data/judge-data-isfinite',
    children: []
  }, {
    menu: '创建对象的方式',
    path: '/data/create-obj',
    children: []
  }]
}, {
  menu: '函数',
  icon: 'icon-marketindex',
  children: [{
    menu: '纯函数',
    path: '/function/pure-function',
    children: []
  }, {
    menu: '闭包',
    path: '/function/closure',
    children: []
  }, {
    menu: '自定义map',
    path: '/function/self-map',
    children: []
  }, {
    menu: '自定义new',
    path: '/function/self-new',
    children: []
  }, {
    menu: '自定义instanceof',
    path: '/function/instanceof',
    children: []
  }, {
    menu: '动态创建js',
    path: '/function/create-js',
    children: []
  }, {
    menu: 'jsonp',
    path: '/function/jsonp',
    children: []
  }, {
    menu: '分时函数',
    path: '/function/time-chunk',
    children: []
  }, {
    menu: '异步管理',
    path: '/function/promise-chunk',
    children: []
  }, {
    menu: '函数柯里化',
    path: '/function/function-currying',
    children: []
  }, {
    menu: '中断forinof',
    path: '/function/for-in-break',
    children: []
  }, {
    menu: '函数类型',
    path: '/function/function-type',
    children: []
  }, {
    menu: 'promise的all-settled',
    path: '/function/all-settled',
    children: []
  }]
}, {
  menu: '组件',
  icon: 'icon-marketindex',
  children: [{
    menu: '无缝轮播',
    path: '/component/carousel',
    children: []
  }, {
    menu: '拖拽组件',
    path: '/component/drag-component',
    children: []
  }, {
    menu: '懒加载',
    path: '/component/lazy-load',
    children: []
  }, {
    menu: '无限加载',
    path: '/component/unlimited-load',
    children: []
  }]
}, {
  menu: '浏览器',
  icon: 'icon-marketindex',
  children: [{
    menu: '判断浏览器种类',
    path: '/browser/browser-type',
    children: []
  }]
},{
  menu: '设计模式',
  icon: 'icon-marketindex',
  children: [{
    menu: '单例模式',
    path: '/browser/browser-type',
    children: []
  },{
    menu: '观察者模式',
    path: '/browser/observer',
    children: []
  },{
    menu: '发布订阅模式',
    path: '/browser/publish-subscribe',
    children: []
  }]
}]
